### ISSUE TITLE
Suggestion: Button activation

### ISSUE THREAD

**Issue by OrbEstCheval** [DrMcCoy/bullseye-ng#1]
I think a button in the left-controls actor tab would make much more sense than the logo. I don't even have the Foundry logo visible in my game, but even if i did, it would be weird for this function to be the one that uses the logo to activate.

**Comment by DrMcCoy** [comment]
I'm open to adding a new button as an alternative way to show the bullseye dialog. I always found it weird that it opened by clicking on the foundry logo, but that wasn't my decision. I see no harm keeping it that way for compatibility reasons, and adding a second way for comfort reasons.

But what do you mean by "left-controls actor tab"? The menu icons on the left side of the screen?

Like so?
![bullseye-new-place](https://user-images.githubusercontent.com/156130/135594212-47ddbf93-b5ce-408f-ad8c-a44761c566e6.png)

What would a good icon to represent this be? I could just drop another bullseye like the one above (or a similar one). I fear that this might be a bit confusing, though.

**Comment by OrbEstCheval** [comment]
A bulleted list icon, like the kind in most text editors, but the dots are bullseyes? Or just two catty-cornered bullseyes might translate okay.

**Comment by DrMcCoy** [comment]
Hmm, using the normal tool buttons, I'm restricted to the icons in the (free version of the) Font Awesome font, it seems. So I used the normal "bullet list" icon, which I hope is okay-ish enough.

It looks like this now:
![bulleyeng5](https://user-images.githubusercontent.com/156130/135687819-5e2a0b98-266a-474d-958d-72f6934cfe92.png)

In either case, it's live now with version 1.1.0: https://github.com/DrMcCoy/bullseye-ng/releases/tag/v1.1.0
