### ISSUE TITLE
Feature Request: Suppress Foundry Logo click area

### ISSUE THREAD

**Issue by napolitanod** [DrMcCoy/bullseye-ng#2]
Thank you for this module! Was wondering if you could include a config setting option to toggle off the right click section in the logo area so it doesn't render or perhaps push it to the player list instead. For those worlds where the logo is suppressed, the click area for this module seems to overlay the scene navigation toggle (because that toggle button pushes to the left corner when the logo is suppressed) and this then prevents the user from toggling the scene nav. A module like Minimal UI has a setting where the foundry logo can be suppressed if you want to see an example.

Thank you!

- Dan

**Comment by DrMcCoy** [comment]
Oh, okay, so supressing the display of the logo doesn't remove the menu click area. That's unfortunate.

In #1, with 1.1.0, I already added a button to the token menu as an alternate means to open the bullseye dialog. I wonder whether a setting to not do the anvil menu even makes any sense, or if should just make the token menu button  canon and remove the anvil menu altogether.

**EDIT**: Or maybe I can even detect if the anvil is hidden and and suppress the right-click area then?

**Comment by QuantumFunks** [comment]
Please as an option to remove the anvil control. The modules that let me hide elements require me to click the anvil and dont work due to this mod.

**Comment by DrMcCoy** [comment]
Okay, the anvil logo menu completely broke in version 9 of Foundry VTT, so I just went ahead and completely removed it with [v1.2.0](https://github.com/DrMcCoy/bullseye-ng/releases/tag/v1.2.0) of Bullseye NG. The canonical way to open Bullseye NG is now by using the new button in the tools menu.
